/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_wheels;
import java.awt.HeadlessException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PlayGOD
 */
public class addsp extends javax.swing.JInternalFrame {

    /**
     * Creates new form addsp
     */
    Connection conn=null;
    PreparedStatement pst=null;
    CallableStatement cst = null;
    ResultSet rs=null;
    public addsp() {
        initComponents();
        conn=DBConnect.connect();
    }

    addsp(String text) {
      jcno.setText(text);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jcsp_table = new javax.swing.JTable();
        jcno = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        badd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pno = new javax.swing.JTextField();
        mrp = new javax.swing.JTextField();
        jdelete = new javax.swing.JButton();
        jupdate = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcsp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jcsp_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcsp_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jcsp_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 211, 1250, 440));

        jcno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcnoActionPerformed(evt);
            }
        });
        jcno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcnoKeyReleased(evt);
            }
        });
        jPanel1.add(jcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 70, 30));

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        jPanel1.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, -1));

        jLabel6.setText("MRP :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 50, 20));

        badd.setText("Add");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });
        jPanel1.add(badd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 120, -1));

        jLabel3.setText("Parts isssued to  JobCard no:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 260, 30));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 54));

        jLabel4.setText("Part No :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 30));

        jLabel5.setText("Quantity :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        pno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnoActionPerformed(evt);
            }
        });
        pno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pnoKeyReleased(evt);
            }
        });
        jPanel1.add(pno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 200, -1));
        jPanel1.add(mrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 80, -1));

        jdelete.setText("Deleted");
        jdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 120, -1));

        jupdate.setText("Update");
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });
        jPanel1.add(jupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcnoActionPerformed

    private void jcnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcnoKeyReleased
        // TODO add your handling code here:
        try {
            String sql="SELECT `partno`, `sqty`, `Mrp` FROM `js_sp` WHERE `jcno`='"+jcno.getText()+"'";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
               tablelord();
            }
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }//GEN-LAST:event_jcnoKeyReleased

    private void pnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnoKeyReleased
        // TODO add your handling code here:
        try {
            String sql="SELECT `MRP` FROM `spares` WHERE `PARTNO`='"+pno.getText()+"'";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
                //qty.setText(rs.getString("Qty"));
                mrp.setText(rs.getString("MRP"));
                
            }
            
            
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }//GEN-LAST:event_pnoKeyReleased

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        // TODO add your handling code here:
        String jno=jcno.getText();
        String p_no=pno.getText();
        String pqty=qty.getText(); 
        String pmrp=mrp.getText();
        Integer totc= Integer.parseInt(pqty)*Integer.parseInt(pmrp);
         try {
            String sql="INSERT INTO `js_sp`(`jcno`, `partno`, `sqty`, `mrp`, `total_cost`) VALUES ('"+jno+"','"+p_no+"','"+pqty+"','"+pmrp+"','"+totc+"')";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            pst.execute();
            tablelord();
            } catch (SQLException e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
         try {
            String sql="{CALL `total_amt`(?)}";
            cst=conn.prepareCall(sql);
            cst.setString(1,jcno.getText());
            cst.executeUpdate();
            } catch (SQLException e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }//GEN-LAST:event_baddActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void pnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnoActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
        // TODO add your handling code here:
        
        try{
            String sql="DELETE FROM `js_sp` WHERE  jcno='"+jcno.getText()+"' AND `partno`='"+pno.getText()+"'";
           PreparedStatement pst1=(PreparedStatement) conn.prepareStatement(sql);
            pst1.execute();
            JOptionPane.showMessageDialog(rootPane,"Delete Success!!!");
            tablelord();
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
         try {
            String sql="{CALL `total_amt`(?)}";
            cst=conn.prepareCall(sql);
            cst.setString(1,jcno.getText());
            cst.executeUpdate();
            } catch (SQLException e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }//GEN-LAST:event_jdeleteActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
        // TODO add your handling code here:
        String jno=jcno.getText();
        String p_no=pno.getText();
        String pqty=qty.getText(); 
        String pmrp=mrp.getText();
        Integer totc= Integer.parseInt(pqty)*Integer.parseInt(pmrp);
        try {
            String sql="UPDATE `js_sp` SET `sqty`='"+pqty+"',`mrp`='"+pmrp+"',`total_cost`='"+totc+"' WHERE `jcno`='"+jno+"' AND`partno`='"+p_no+"'";
            pst=(PreparedStatement) conn.prepareStatement(sql);
       
            pst.execute();
            tablelord();
            } catch (SQLException e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
         try {
            String sql="{CALL `total_amt`(?)}";
            cst=conn.prepareCall(sql);
            cst.setString(1,jcno.getText());
            cst.executeUpdate();
            } catch (SQLException e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }//GEN-LAST:event_jupdateActionPerformed

    private void jcsp_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcsp_tableMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel tmodel=(DefaultTableModel)jcsp_table.getModel();
        int selectrowindex=jcsp_table.getSelectedRow();
        
        jcno.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        pno.setText(tmodel.getValueAt(selectrowindex, 1).toString());
        qty.setText(tmodel.getValueAt(selectrowindex, 2).toString());
        mrp.setText(tmodel.getValueAt(selectrowindex, 3).toString());
        
        
    }//GEN-LAST:event_jcsp_tableMouseClicked

     private void tablelord()
    {
        try {
            String sql="SELECT * FROM `js_sp` WHERE `jcno`='"+jcno.getText()+"'";
            pst=(com.mysql.jdbc.PreparedStatement) conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jcsp_table.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jcno;
    private javax.swing.JTable jcsp_table;
    private javax.swing.JButton jdelete;
    private javax.swing.JButton jupdate;
    private javax.swing.JTextField mrp;
    private javax.swing.JTextField pno;
    private javax.swing.JTextField qty;
    // End of variables declaration//GEN-END:variables
}
