/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_wheels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author PlayGOD
 */
public class Bill extends javax.swing.JInternalFrame {

    /**
     * Creates new form Spares
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public Bill() {
        initComponents();
        conn=DBConnect.connect();
        autoBno();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcno = new javax.swing.JTextField();
        bno = new javax.swing.JTextField();
        bsave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jctable = new javax.swing.JTable();
        bamt = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Total Bill Amout:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 546, 110, 30));

        jcno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcnoActionPerformed(evt);
            }
        });
        jcno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcnoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcnoKeyTyped(evt);
            }
        });
        jPanel1.add(jcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, -1));

        bno.setEditable(false);
        bno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnoActionPerformed(evt);
            }
        });
        jPanel1.add(bno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 180, -1));

        bsave.setText("Save");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel1.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 150, -1));

        jLabel1.setText("Bill No :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel2.setText("JC NO :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 93, -1, -1));

        jctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jctable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 211, 1200, 310));
        jPanel1.add(bamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 550, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnoActionPerformed

    private void jcnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcnoActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        // TODO add your handling code here:
        String billno=bno.getText();
        String jno=jcno.getText();
        String amt=bamt.getText();
          try{
            String sql="INSERT INTO `bill`(`bill_no`, `JC_no`, `TotalBill_amt`) VALUES ('"+billno+"', '"+jno+"', '"+amt+"') ";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Successfully inserted !!!");
         
        }   catch (SQLException e){
            JOptionPane.showMessageDialog(rootPane,e);
        }
        clearfield();
        autoBno();
    }//GEN-LAST:event_bsaveActionPerformed

    private void jcnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcnoKeyReleased
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_jcnoKeyReleased

    private void jcnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcnoKeyTyped
        // TODO add your handling code here:
         tablelord();
         billamt();
    }//GEN-LAST:event_jcnoKeyTyped

    private void autoBno(){
        try{
            String sql="SELECT `Bill_No` FROM `bill` ORDER BY Bill_No DESC LIMIT 1";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
                 String rnno=rs.getString("Bill_No");
                 int co=rnno.length();
                 String txt=rnno.substring(0,2);
                 String num=rnno.substring(2,co);
                 int n=Integer.parseInt(num);
                 n++;
                 String snum=Integer.toString(n);
                 String ftxt=txt+snum;
                 bno.setText(ftxt);
            }
            else{
                bno.setText("SP1");
                        
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
         private void tablelord()
    {
        try {
            String sql="SELECT `partno`, `sqty`, `mrp`, `total_cost` FROM `js_sp` WHERE `jcno`='"+jcno.getText()+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jctable.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
              
    }
       private void billamt(){
          try {
            String sql="SELECT `Bill_amt` FROM `jobcard` WHERE `JC_no`='"+jcno.getText()+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
            String pqr = rs.getString("Bill_amt");
           bamt.setText(pqr);
            } 
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
           
       }
       private void clearfield(){
     //   bno.setText("");
        jcno.setText("");
       
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bamt;
    private javax.swing.JTextField bno;
    private javax.swing.JButton bsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jcno;
    private javax.swing.JTable jctable;
    // End of variables declaration//GEN-END:variables
}
