/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_wheels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author PlayGOD
 */
public class History extends javax.swing.JInternalFrame {

    /**
     * Creates new form Spares
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public History() {
        initComponents();
        conn=DBConnect.connect();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        htable = new javax.swing.JTable();
        regno = new javax.swing.JTextField();
        mcolor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        phno = new javax.swing.JTextField();
        model = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JLABEL1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        htable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(htable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 1260, 340));

        regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoActionPerformed(evt);
            }
        });
        regno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                regnoKeyReleased(evt);
            }
        });
        jPanel1.add(regno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 120, -1));

        mcolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-COLOUR-", "RED", "BLUE", "BLACK", "WHITE", "GREEN", " ", " " }));
        mcolor.setToolTipText("");
        mcolor.setEnabled(false);
        mcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcolorActionPerformed(evt);
            }
        });
        jPanel1.add(mcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, 30));

        jLabel4.setText("Customer Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, -1));

        phno.setEditable(false);
        phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnoActionPerformed(evt);
            }
        });
        jPanel1.add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 160, 30));

        model.setEditable(false);
        jPanel1.add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 160, 30));

        cname.setEditable(false);
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        jPanel1.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, 30));

        jLabel7.setText("Phone NO :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 30));

        jLabel8.setText("Model");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 140, 30));

        jLabel3.setText("Reg NO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, -1, -1));

        JLABEL1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        JLABEL1.setText("  History");
        JLABEL1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(JLABEL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1260, 90));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1260, 190));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoActionPerformed

    private void regnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regnoKeyReleased
        // TODO add your handling code here:
        try {
            String sql="SELECT `Cname`, `Phno`, `Model`, `Colour` FROM `vehicle` WHERE Regno='"+regno.getText()+"'";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
                cname.setText(rs.getString("Cname"));
                phno.setText(rs.getString("Phno"));
                model.setText(rs.getString("Model"));
                mcolor.setSelectedItem(rs.getString("Colour"));
            }
            tablelord();
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
        
        
    }//GEN-LAST:event_regnoKeyReleased

    private void mcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcolorActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void phnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnoActionPerformed
    private void tablelord()
    {
        try {
            String sql="SELECT `JC_no`,`jc_Date`, `kms`, `mech_name`, `Status`, `Bill_amt` FROM `jobcard` WHERE `Regno`='"+regno.getText()+"'";
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            htable.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
              
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLABEL1;
    private javax.swing.JTextField cname;
    private javax.swing.JTable htable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mcolor;
    private javax.swing.JTextField model;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField regno;
    // End of variables declaration//GEN-END:variables
}
