/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_wheels;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PlayGOD
 */
public class Jobcard extends javax.swing.JInternalFrame {

    /**
     * Creates new form Spares
     */
    Connection conn=null;
    PreparedStatement pst=null;
    
    
    ResultSet rs=null;
    public Jobcard() {
        initComponents();
        conn=DBConnect.connect();
        LocalDate today=LocalDate.now();
        refdate.setText(today.toString());
        autoId();
        tablelord();
    }

    public Jobcard(JButton binsert, JTextField cname, JLabel jLabel1, JLabel jLabel10, JLabel jLabel11, JLabel jLabel12, JLabel jLabel2, JLabel jLabel3, JLabel jLabel4, JLabel jLabel5, JLabel jLabel6, JLabel jLabel7, JLabel jLabel8, JLabel jLabel9, JPanel jPanel1, JScrollPane jScrollPane1, JTable jTable1, JTextField jcno, JTextField kms, JComboBox<String> mcolor, JTextField mname, JTextField model, JTextField phno, JTextField refdate, JTextField regno, JTextField status) {
        this.binsert = binsert;
        this.cname = cname;
        this.jLabel1 = jLabel1;
        this.jLabel10 = jLabel10;
        this.jLabel11 = jLabel11;
        this.jLabel12 = jLabel12;
        this.jLabel2 = jLabel2;
        this.jLabel3 = jLabel3;
        this.jLabel4 = jLabel4;
        this.jLabel5 = jLabel5;
        this.jLabel6 = jLabel6;
        this.jLabel7 = jLabel7;
        this.jLabel8 = jLabel8;
        this.jLabel9 = jLabel9;
        this.jPanel1 = jPanel1;
        this.jScrollPane1 = jScrollPane1;
        this.sptable = jTable1;
        this.jcno = jcno;
        this.kms = kms;
        this.mcolor = mcolor;
        this.mname = mname;
        this.model = model;
        this.phno = phno;
        this.refdate = refdate;
        this.regno = regno;
        this.status = status;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        binsert = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jcno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        billamt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        regno = new javax.swing.JTextField();
        model = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        refdate = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        kms = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        mcolor = new javax.swing.JComboBox<>();
        phno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sptable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        binsert.setText("Insert");
        binsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binsertActionPerformed(evt);
            }
        });
        jPanel1.add(binsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 110, 40));

        bdelete.setText("Delete");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 120, 40));

        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });
        jPanel1.add(bupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 120, 40));

        jLabel2.setText("JC NO :");
        jLabel2.setPreferredSize(new java.awt.Dimension(20, 30));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 110, -1));

        jcno.setEditable(false);
        jcno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcnoActionPerformed(evt);
            }
        });
        jPanel1.add(jcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 3, 48)); // NOI18N
        jLabel1.setText("Job Card");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1270, 90));

        jlabel15.setText("Bill Amount :");
        jPanel1.add(jlabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 310, 80, 40));

        jLabel3.setText("Reg NO :");
        jLabel3.setPreferredSize(new java.awt.Dimension(20, 30));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, 30));

        jLabel4.setText("Customer Name :");
        jLabel4.setPreferredSize(new java.awt.Dimension(20, 30));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 140, -1));

        billamt.setEditable(false);
        billamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billamtActionPerformed(evt);
            }
        });
        jPanel1.add(billamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 320, 80, 30));

        jLabel10.setText("Mechanic Name :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 100, 30));

        regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoActionPerformed(evt);
            }
        });
        regno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                regnoKeyReleased(evt);
            }
        });
        jPanel1.add(regno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 160, 30));
        jPanel1.add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 160, 30));

        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        jPanel1.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 160, 30));

        jLabel9.setText(" Kms :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 100, 40));

        jLabel7.setText("Phone NO :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 30));

        jLabel11.setText("Status");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 90, 30));

        jLabel12.setText("Reference Date :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 100, 20));

        refdate.setEditable(false);
        refdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refdateActionPerformed(evt);
            }
        });
        jPanel1.add(refdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 322, 130, 30));

        status.setEditable(false);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, 130, 30));

        kms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmsActionPerformed(evt);
            }
        });
        jPanel1.add(kms, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 162, 130, 30));
        jPanel1.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 130, 30));

        mcolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT COLOUR-", "RED", "BLUE", "BLACK", "WHITE", "GREEN", " ", " " }));
        mcolor.setToolTipText("");
        mcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcolorActionPerformed(evt);
            }
        });
        jPanel1.add(mcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnoActionPerformed(evt);
            }
        });
        jPanel1.add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 160, 30));

        jLabel8.setText("Model");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, 30));

        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 620, 240));

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 570, 240));

        sptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        sptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sptable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 1250, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void jcnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcnoActionPerformed

    private void regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoActionPerformed

    private void phnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnoActionPerformed

    private void mcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcolorActionPerformed

    private void kmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kmsActionPerformed

    private void refdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refdateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_refdateActionPerformed

    private void binsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binsertActionPerformed
        // TODO add your handling code here:
                 
       String jno=jcno.getText();
       String vrno=regno.getText();
       String custname=cname.getText();
       String pno=phno.getText();
       String modl=model.getText();
       String vcolr=mcolor.getSelectedItem().toString();
       String odo=kms.getText();
       String mechname=mname.getText();
       String rdate=refdate.getText();
       String stus=status.getText();

       
       
            try {
                 try{
                      String sql="INSERT INTO `jobcard`(`JC_no`, `Regno`, `jc_Date`, `kms`, `mech_name`, `Status`, `Cname`, `Phno`, `Model`, `Colour`) VALUES ('"+jno+"','"+vrno+"','"+rdate+"','"+odo+"','"+mechname+"','"+stus+"','"+custname+"','"+pno+"','"+modl+"','"+vcolr+"')";
                 PreparedStatement pstt=conn.prepareStatement(sql);
                 pstt.execute();
                    
                 } catch(SQLException e){
                     String sql="INSERT INTO `vehicle`(`Regno`, `Cname`, `Phno`, `Model`, `Colour`) VALUES ('"+vrno+"','"+custname+"','"+pno+"','"+modl+"','"+vcolr+"')" ;
                     PreparedStatement pst2=conn.prepareStatement(sql);
                     pst2.execute();
                     String sql1="INSERT INTO `jobcard`(`JC_no`, `Regno`, `jc_Date`, `kms`, `mech_name`, `Status`) VALUES ('"+jno+"','"+vrno+"','"+rdate+"','"+odo+"','"+mechname+"','"+stus+"')";
                     PreparedStatement pst1=conn.prepareStatement(sql1);
                     pst1.execute();
                                     
                 }
                 JOptionPane.showMessageDialog(rootPane, "Successfully insert");
                 
                
        } catch (Exception e) {
            
                
                JOptionPane.showMessageDialog(rootPane, e);
        }
        clearFild();
        autoId();
        tablelord();

    }//GEN-LAST:event_binsertActionPerformed

    private void sptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sptableMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel tmodel=(DefaultTableModel)sptable.getModel();
        int selectrowindex=sptable.getSelectedRow();
        jcno.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        
           
       
        regno.setText(tmodel.getValueAt(selectrowindex, 1).toString());
        refdate.setText(tmodel.getValueAt(selectrowindex, 2).toString());
        kms.setText(tmodel.getValueAt(selectrowindex, 3).toString());
        mname.setText(tmodel.getValueAt(selectrowindex, 4).toString());
        phno.setText(tmodel.getValueAt(selectrowindex, 6).toString());
        model.setText(tmodel.getValueAt(selectrowindex, 7).toString());
        cname.setText(tmodel.getValueAt(selectrowindex, 5).toString());
        status.setText(tmodel.getValueAt(selectrowindex, 9).toString());
        mcolor.setSelectedItem(tmodel.getValueAt(selectrowindex, 8).toString());
        billamt.setText(tmodel.getValueAt(selectrowindex,10).toString());
    }//GEN-LAST:event_sptableMouseClicked

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        // TODO add your handling code here:
       String jno=jcno.getText();
       String vrno=regno.getText();
       String custname=cname.getText();
       String pno=phno.getText();
       String modl=model.getText();
       String vcolr=mcolor.getSelectedItem().toString();
       String odo=kms.getText();
       String mechname=mname.getText();
       String rdate=refdate.getText();
       String stus=status.getText();
        
        try {
            String  sql = "UPDATE `jobcard` SET `Regno`='"+vrno+"',`jc_Date`='"+rdate+"',`kms`='"+odo+"',`mech_name`='"+mechname+"',`cname`='"+custname+"',`phno`='"+pno+"',`model`='"+modl+"',`colour`='"+vcolr+"' WHERE `JC_no`='"+jno+"'";
         pst=conn.prepareStatement(sql);
         pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Update success");
            tablelord();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_bupdateActionPerformed

    private void regnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regnoKeyReleased
        // TODO add your handling code here:
         try {
            String sql="SELECT `Cname`, `Phno`, `Model`, `Colour` FROM `vehicle` WHERE Regno='"+regno.getText()+"'";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
                cname.setText(rs.getString("Cname"));
                phno.setText(rs.getString("Phno"));
                model.setText(rs.getString("Model"));
                mcolor.setSelectedItem(rs.getString("Colour"));
            }
            
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_regnoKeyReleased

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
         try{
            String sql="DELETE FROM `jobcard` WHERE JC_no='"+jcno.getText()+"'";
           PreparedStatement pst=(PreparedStatement) conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Delete Success!!!");
            tablelord();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void billamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billamtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billamtActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void clearFild()
    {
    
        
       regno.setText("");
       cname.setText("");
       status.setText("");
       mname.setText("");
       phno.setText("");
       model.setText("");
       kms.setText("");
       mcolor.setSelectedIndex(0);
       billamt.setText("");
    
    }

     private void tablelord()
    {
        try {
            String sql="SELECT `JC_no`, `Regno`, `jc_Date`, `kms`, `mech_name`, `cname`, `phno`, `model`, `colour`, `Status`,`Bill_Amt` FROM `jobcard`";
            pst=(com.mysql.jdbc.PreparedStatement) conn.prepareStatement(sql);
            rs=pst.executeQuery();
            sptable.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
      
    }
    
    private void autoId()
    {
        try {
             String sql="SELECT `JC_no` FROM `jobcard` ORDER BY JC_no DESC LIMIT 1";
         
            pst=(com.mysql.jdbc.PreparedStatement) conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next())
           {
                String rnno=rs.getString("JC_no");
                int co=rnno.length();
               String txt= rnno.substring(0, 2);
               String num=rnno.substring(2, co);
               int n=Integer.parseInt(num);
               n++;
               String snum=Integer.toString(n);
               String ftxt=txt+snum;
               jcno.setText(ftxt);
               status.setText("Pending");
            
           }
           else
           {
               jcno.setText("jc1");
                status.setText("Pending");
           }
           
                            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdelete;
    private javax.swing.JTextField billamt;
    private javax.swing.JButton binsert;
    private javax.swing.JButton bupdate;
    private javax.swing.JTextField cname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jcno;
    private javax.swing.JLabel jlabel15;
    private javax.swing.JTextField kms;
    private javax.swing.JComboBox<String> mcolor;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField model;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField refdate;
    private javax.swing.JTextField regno;
    private javax.swing.JTable sptable;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
