/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_wheels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PlayGOD
 */
public class Spares extends javax.swing.JInternalFrame {

    /**
     * Creates new form Spares
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public Spares() {
        initComponents();
        conn=DBConnect.connect();
        tablelord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p_no = new javax.swing.JTextField();
        btp_add = new javax.swing.JButton();
        btp_update = new javax.swing.JButton();
        btp_del = new javax.swing.JButton();
        p_name = new javax.swing.JTextField();
        p_loc = new javax.swing.JTextField();
        p_mrp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        p_table = new javax.swing.JTable();
        p_qty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_noActionPerformed(evt);
            }
        });
        jPanel1.add(p_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 102, 180, 40));

        btp_add.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        btp_add.setText("ADD");
        btp_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btp_addActionPerformed(evt);
            }
        });
        jPanel1.add(btp_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 120, 130, -1));

        btp_update.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        btp_update.setText("Update");
        btp_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btp_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btp_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 210, 130, -1));

        btp_del.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        btp_del.setText("Delete");
        btp_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btp_delActionPerformed(evt);
            }
        });
        jPanel1.add(btp_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 300, 130, -1));

        p_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_nameActionPerformed(evt);
            }
        });
        jPanel1.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 162, 180, 40));
        jPanel1.add(p_loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 180, 40));

        p_mrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_mrpActionPerformed(evt);
            }
        });
        jPanel1.add(p_mrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 180, 40));

        p_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        p_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(p_table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 411, 1230, 220));
        jPanel1.add(p_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 322, 180, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel6.setText("Location :");
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setText("Part Name :");
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel7.setText("MRP :");
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setText("Part no :");
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 140, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel8.setText("Quantity :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 130, 30));

        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 90, 290, 290));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1260, 290));

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 3, 48)); // NOI18N
        jLabel2.setText("  Spares");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 80));

        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_noActionPerformed

    private void p_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_nameActionPerformed

    private void p_mrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_mrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_mrpActionPerformed

    private void btp_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btp_addActionPerformed
        // TODO add your handling code here:
        String pno=p_no.getText();
        String pname=p_name.getText();
        String ploc=p_loc.getText();
        String pmrp=p_mrp.getText();
        String pqty=p_qty.getText();
       
        try{
            String sql="INSERT INTO `spares` (`PARTNO`, `PNAME`, `LOCATION`, `MRP`, `Qty`) VALUES ('"+pno+"', '"+pname+"', '"+ploc+"', '"+pmrp+"', '"+pqty+"') ";
            PreparedStatement pst=(PreparedStatement) conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Successfully inserted !!!");
         
        }   catch (Exception e){
            JOptionPane.showMessageDialog(rootPane,e);
        }
        clearfield();
        tablelord();
    }//GEN-LAST:event_btp_addActionPerformed

    private void p_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_tableMouseClicked
        // TODO add your handling code here:
            DefaultTableModel tmodel=(DefaultTableModel)p_table.getModel();
            int selectrowindex=p_table.getSelectedRow();
            p_no.setText(tmodel.getValueAt(selectrowindex, 0).toString());
            p_name.setText(tmodel.getValueAt(selectrowindex, 1).toString());
            p_loc.setText(tmodel.getValueAt(selectrowindex, 2).toString());
            p_mrp.setText(tmodel.getValueAt(selectrowindex, 3).toString());
            p_qty.setText(tmodel.getValueAt(selectrowindex, 4).toString());
        
    }//GEN-LAST:event_p_tableMouseClicked

    private void btp_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btp_updateActionPerformed
        // TODO add your handling code here:
        String pno=p_no.getText();
        String pname=p_name.getText();
        String ploc=p_loc.getText();
        String pmrp=p_mrp.getText();
        String pqty=p_qty.getText();
        
        try{    
            String sql="UPDATE `spares` SET `PNAME`='"+pname+"',`LOCATION`='"+ploc+"',`MRP`='"+pmrp+"',`Qty`='"+pqty+"' WHERE `PARTNO`='"+pno+"'";
            PreparedStatement pst=(PreparedStatement) conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Successfully Updated !!!");
            tablelord();
         
        }   catch (Exception e){
            JOptionPane.showMessageDialog(rootPane,e);
        }
        
    }//GEN-LAST:event_btp_updateActionPerformed

    private void btp_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btp_delActionPerformed
        // TODO add your handling code here:
        
        try{
            String sql="DELETE FROM `spares` WHERE PARTNO='"+p_no.getText()+"'";
           PreparedStatement pst=(PreparedStatement) conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Delete Success!!!");
            tablelord();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
        
    }//GEN-LAST:event_btp_delActionPerformed
    
    private void tablelord(){
        
        try{
            String sql=" SELECT * FROM `spares` ";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs=pst.executeQuery();
            p_table.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch(Exception e) {
            JOptionPane.showConfirmDialog(rootPane ,e);
        }
        
    }
    
    private void clearfield(){
        p_no.setText("");
        p_name.setText("");
        p_loc.setText("");
        p_mrp.setText("");
        p_qty.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btp_add;
    private javax.swing.JButton btp_del;
    private javax.swing.JButton btp_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField p_loc;
    private javax.swing.JTextField p_mrp;
    private javax.swing.JTextField p_name;
    private javax.swing.JTextField p_no;
    private javax.swing.JTextField p_qty;
    private javax.swing.JTable p_table;
    // End of variables declaration//GEN-END:variables
}
